---
title: "Unsupervised Report"
author: "Tay Jing Rui"
output: html_document
---

# Data Summary

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(corrplot)
library(tidyr)
library(ggplot2)
library(corrplot)
library(reshape2)
library(dbscan)
library(cluster)
library(GGally)
raw_data <- tar_read(raw_data)
cleaned_data <- tar_read(cleaned_data)
eda_results <- tar_read(eda_results)
pca <- tar_read(pca)
kmeans_summary <- tar_read(kmeans_summary)
dbscan_summary <- tar_read(dbscan_summary)
silhouette_kmeans <- tar_read(silhouette_kmeans)
```

# Introduction

# EDA
```{r}
summary(cleaned_data)
# Histograms and boxplots of features
eda_results$histograms
eda_results$boxplots
corrplot(cor(select(cleaned_data, -id)), method = "color")
```

# PCA
```{r}
summary(pca)
plot(pca, type="lines") # Scree plot
biplot(pca, scale=0)
```

# Clustering
```{r}
# K-means results
kmeans_summary
cat("K-means silhouette score:", silhouette_kmeans, "\n")
# DBSCAN results
dbscan_summary
```

# Interpretation